name: Build
on:
  pull_request:
    branches: [main]
  workflow_dispatch: {}
jobs:
  build-project:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    env:
      CI: "true"
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --checkfiles
      - run: yarn projen
      - run: yarn run build

