name: Build
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  build-project:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    env:
      CI: "true"
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --checkfiles
      - run: yarn projen
      - name: Anti-tamper check
        run: git diff --exit-code
      - name: Set git identity
        run: |-
          git config user.name "Auto-bump"
          git config user.email "github-actions@github.com"
      - run: yarn run build
      - name: Anti-tamper check
        run: git diff --exit-code
